### ISSUE TITLE
Not parallaxing when height element at 100%

### ISSUE THREAD

**Issue by rahendz** [jaicab/Paraxify.js#12]
i found the problem what my previous issue at [here](https://github.com/jaicab/Paraxify.js/issues/3#issuecomment-269300638), parallaxing not work when element had 100% or 100vh height. i'm not a javascript coder so i don't know how to read the plugin to fix it.

But is there other way to make it parallaxing even the element in 100% height? any suggestion? i build a theme here which have a header with 100% height and need parallax for it.

**Comment by widoz** [comment]
Same issue with height: 100vh.

I temporary solved by using this snippet within the _check() method:

`
if(actualHeight !== main.offsetHeight) {
    main.diff = -(actualHeight - main.offsetHeight);
} else {
    main.diff = -actualHeight;
}
`

On my page the issue was that main.diff will always get 0 because on load the actualHeight and main.offsetHeight were the same.

So during the first time the .diff property is set the value 0 will be multiply within the _animate() method `position = pho[i].diff * (per - 0.5);`.

**Comment by rahendz** [comment]
@widoz nice fix, thanks man. it really help me.
